@NarouBackend_HostAddress = http://localhost:5202

GET {{NarouBackend_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer CfDJ8EyyE-3WjlBNrTld30LHbOKvuydYuydkBaZ_KAeLHxtI00vdyhd_3J0tMQ1UD1Ai55GdLIssCbec0B9CC5wk3Hjh640MsNDefsF2fptXBUORnEQaMkWEs0GSKMR5BhoK_hgeGfJhmsJt2AGa2XlrYRxK1qql2p_br9XQxHK0mXUkG_xQDy7AxIUl2JcZ8D_Q6vngBOs7xYy9xxbq-Ueaiym5YzUrYH014Q67ChWEeshzBu_NWZaE5Zyaibnnr4nDnGWHO_HTNYjVeP9TuPd-Mv7dMISBPjPAc9zzbdwzSrWXAu_DcTeyHNx1_FUK9Khd1ZRaNjjBL9FDDUl10wewOkg9B4B42cZ7ciZOXCuxeSehGYPNM4RMV8EoAcDzlwCl-lWCAq84pRzCvreBU_XrvYJirQB6Xi67XIk1_NzoVyhc7n8xpP0GZzWtIyFEeu3OCYrATc9d1SPOF_jKJW-ncbfsWHR9k7lWf6S8u2Us3RmrSrrjQrnRGwfu98xmiJYFxhsRCmmbH0RMGB_6mNevLW8Aasb7uPzx9i8c5F2tW1VElRRECAM6r1fzIb64SrqtY-G-U_YQXGGYJU-0IaeP6YZObgKWuyHqmyS05aRZRbzdLmkib7FaYZNz6ePniqXqmT-w9MFKuJh7IouKhpos3NsW8ntt-KOxhHX_j4qdiDKugTiy0jbtDNuPvuy-3F-fDAawb0BkOfdIQMBTbQ_GNO8

###
